[build-system]
requires = ["setuptools"]

[project]
name = "govee-local-api"
version = "0.1.0"
authors = [
  { name="Galorhallen", email="andrea.ponte1987@gmail.com" },
]
description = "Library to comunicate with Govee local API"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Galorhallen/govee-local-api"
"Bug Tracker" = "https://github.com/Galorhallen/govee-local-api/issues"

[tool.black]
target-version = ["py310"]